---
# ---------------------------------------------------------
# 変数表示の実行
# ---------------------------------------------------------
- name: Task level variable check
  ansible.builtin.debug:
    msg: "タスク変数がない場合: {{ test_var }}"